language: rust
sudo: required
services:
  - docker
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
- cargo build --verbose --examples
- cargo test
- ./scripts/docker-examples-test.sh
